export const browserCoreExamples = [
  "seksbot browser status",
  "seksbot browser start",
  "seksbot browser stop",
  "seksbot browser tabs",
  "seksbot browser open https://example.com",
  "seksbot browser focus abcd1234",
  "seksbot browser close abcd1234",
  "seksbot browser screenshot",
  "seksbot browser screenshot --full-page",
  "seksbot browser screenshot --ref 12",
  "seksbot browser snapshot",
  "seksbot browser snapshot --format aria --limit 200",
  "seksbot browser snapshot --efficient",
  "seksbot browser snapshot --labels",
];

export const browserActionExamples = [
  "seksbot browser navigate https://example.com",
  "seksbot browser resize 1280 720",
  "seksbot browser click 12 --double",
  'seksbot browser type 23 "hello" --submit',
  "seksbot browser press Enter",
  "seksbot browser hover 44",
  "seksbot browser drag 10 11",
  "seksbot browser select 9 OptionA OptionB",
  "seksbot browser upload /tmp/file.pdf",
  'seksbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "seksbot browser dialog --accept",
  'seksbot browser wait --text "Done"',
  "seksbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "seksbot browser console --level error",
  "seksbot browser pdf",
];
